@api = http://localhost:4000/tasks


GET {{api}}

###
GET {{api}}/1


###
GET {{api}}/count

###
POST {{api}}
Content-Type: application/json
{
    "title":"sadas",
    "descripcion":"asdasdadsasd",
    "image": "aaaaaaaaaaaaaaaa"
}